apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: restapi
  namespace: restapi
spec:
  chart:
    spec:
      version: ">=1.0.0"
  values:
    ingress:
      hosts:
        - host: restapi.production
          paths:
            - path: /
              pathType: ImplementationSpecific
